### ISSUE TITLE
value of translate3d  changed when click by zoom up

### ISSUE THREAD

**Issue by abratko** [worka/vanilla-js-wheel-zoom#10]
I want to scale only image. Image size is 2082x2596. Visible layout is 960x1024.

Here are my html and less.

``` html
<div class="zoom-window-container">
                    <div id="zoomWindow" class="zoom-window" style="cursor: grab;">
                        <img id="metroMap" class="zoom-window__content" src="/uploads/media/metro_timeline/0002/19/87e3974caeaadc5b849f9aed330b07a9c1beb3da.png" style="transform: translate3d(0px, 0px, 0px) scale(0.461095);">
                    </div>
                </div>
```
less 
``` less

.zoom-window-container {
  position: relative;
  display: block;
  padding: 0;
  overflow: hidden;

  width: 960px;
  height: 1204px;


  .zoom-window {
    display: flex;
    align-items: center;
    justify-content: center;

    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 100%;
    border: 0;

    .zoom-window__content {
      position: relative;
      display: flex;
      align-items: center;
    }

  }
}
```

I coped this from https://worka.github.io/vanilla-js-wheel-zoom/demo-image.html

But when i click by zoom up, value of transform  set up in  translate3d(0px, -435.758px, 0px) scale(0.627762);

But in your example it is  translate3d(0px, 0px, 0px)

Can you help? Where ir issue?
